### ISSUE TITLE
Add getters for GPS time data

### ISSUE THREAD

**Issue by theduke** [felixc/rexiv2#31]
Hey, great crate!

An awesome addition would be getters for the GPS date/time fields that return chrono types.

sample values:
```rust
    GPSDateStamp: "2010:09:28"
    GPSDateTime: "2016:09:19 23:07:17Z"
```

**Comment by felixc** [comment]
Hi! Thanks for the suggestion! Do you know where those fields might usually be found? E.g. in XMP, IPTC, EXIF, or somewhere else? Under what name?

I ask because skimming the upstream gexiv2 docs I don't see GPS timestamps mentioned. To support this might mean first adding an accessor function upstream — unless there's a specific existing tag we can read from in a generic way?

**Comment by felixc** [comment]
Closing this for now since I'm not aware of anything upstream that would let us do this, but I'd be very happy to have this functionality if anyone were to find a mechanism for it! Thanks for the suggestion!
